"""Rule-based context classification patterns."""

from __future__ import annotations

from dataclasses import dataclass

from adaptive_soundscape.core.events import WorkContext


@dataclass(frozen=True)
class ContextRule:
    context: WorkContext
    process_names: tuple[str, ...] = ()
    title_keywords: tuple[str, ...] = ()
    weight: float = 1.0


# Browsers alone are not treated as distraction; see classifier._score_distraction.
BROWSER_PROCESS_HINTS: tuple[str, ...] = (
    "chrome",
    "msedge",
    "firefox",
    "brave",
    "opera",
    "vivaldi",
)

# Productive browser tabs should not trigger distraction scoring.
WORK_BROWSER_KEYWORDS: tuple[str, ...] = (
    "stackoverflow",
    "stack overflow",
    "github",
    "gitlab",
    "bitbucket",
    "documentation",
    "docs.",
    "developer.",
    "devdocs",
    "mdn",
    "readthedocs",
    "localhost",
    "127.0.0.1",
    "pull request",
    "merge request",
    "issue #",
    "jira",
    "confluence",
    "notion",
    "wikipedia",
    "arxiv",
    "pypi",
    "npm",
    "api reference",
)

# Source file extensions in window titles strongly suggest coding.
CODE_FILE_EXTENSIONS: tuple[str, ...] = (
    ".py",
    ".js",
    ".ts",
    ".tsx",
    ".jsx",
    ".java",
    ".go",
    ".rs",
    ".cpp",
    ".c",
    ".h",
    ".cs",
    ".rb",
    ".php",
    ".swift",
    ".kt",
    ".scala",
    ".vue",
    ".sql",
    ".yaml",
    ".yml",
    ".toml",
    ".json",
    ".md",
)

DEFAULT_RULES: tuple[ContextRule, ...] = (
    ContextRule(
        WorkContext.PROGRAMMING,
        process_names=(
            "code",
            "devenv",
            "cursor",
            "pycharm",
            "pycharm64",
            "idea64",
            "idea",
            "webstorm64",
            "webstorm",
            "goland64",
            "goland",
            "rider64",
            "rider",
            "clion64",
            "clion",
            "phpstorm64",
            "phpstorm",
            "rubymine64",
            "rubymine",
            "datagrip64",
            "datagrip",
            "fleet",
            "androidstudio64",
            "studio64",
            "sublime_text",
            "notepad++",
            "nvim",
            "vim",
            "emacs",
            "windowsterminal",
            "wt",
            "powershell",
            "pwsh",
            "cmd",
            "bash",
            "wsl",
        ),
        title_keywords=(
            "visual studio",
            "vscode",
            "vs code",
            "cursor",
            "pycharm",
            "intellij",
            "webstorm",
            "goland",
            "rider",
            "clion",
            "phpstorm",
            "jetbrains",
            "debug",
            "breakpoint",
            "git ",
            " - github",
            "pull request",
            "merge request",
        ),
        weight=1.25,
    ),
    ContextRule(
        WorkContext.TEAM_WORKFLOW,
        process_names=("teams", "slack", "zoom", "outlook", "discord", "webex"),
        title_keywords=(
            "microsoft teams",
            "teams |",
            "slack |",
            "zoom meeting",
            "zoom -",
            "google meet",
            "outlook",
            "calendar",
            "mail -",
            "discord",
        ),
        weight=1.0,
    ),
    ContextRule(
        WorkContext.READING_WRITING,
        process_names=("winword", "notepad", "notion", "obsidian"),
        title_keywords=(
            "microsoft word",
            " - word",
            "notion",
            "obsidian",
            "document",
            "reading",
            "manuscript",
            "essay",
        ),
        weight=1.0,
    ),
    ContextRule(
        WorkContext.SCIENTIFIC,
        process_names=("matlab", "wolfram", "jupyter", "spyder", "stata", "spss"),
        title_keywords=(
            "jupyter",
            "matlab",
            "wolfram",
            "notebook",
            "research",
            "arxiv",
            "dataset",
            "laboratory",
        ),
        weight=1.1,
    ),
    ContextRule(
        WorkContext.CREATIVE_DESIGN,
        process_names=(
            "figma",
            "photoshop",
            "blender",
            "illustrator",
            "indesign",
            "premiere",
            "afterfx",
            "davinci",
        ),
        title_keywords=(
            "figma",
            "photoshop",
            "design",
            "blender",
            "illustrator",
            "canvas",
            "premiere",
            "after effects",
        ),
        weight=1.0,
    ),
    ContextRule(
        WorkContext.DISTRACTION,
        process_names=(),
        title_keywords=(
            "youtube",
            "twitter",
            "reddit",
            "facebook",
            "instagram",
            "tiktok",
            "twitch",
            "netflix",
            "game",
            "gaming",
            "steam",
            "spotify",
        ),
        weight=1.0,
    ),
)
